import {
  RiArrowUpSLine,
  RiThumbUpFill,
  RiThumbUpLine,
  RiThumbDownFill,
  RiThumbDownLine,
  RiLineChartLine,
  RiStickyNote2Fill,
  RiDeleteBinLine,
  RiDraggable,
  RiPuzzleFill,
  RiPriceTag3Fill,
  RiEdit2Fill,
  RiFileCopyFill,
  RiBookmarkLine,
  RiDeleteBin6Fill,
  RiMore2Line,
  RiCloseLargeLine,
  RiLayout3Line,
  RiTerminalBoxFill,
  RiTerminalWindowFill,
  RiCalculatorFill,
  RiCheckboxMultipleFill,
  RiHealthBookFill,
  RiSurveyFill,
  RiMessage3Fill,
  RiQuestionFill,
  RiAlertFill,
  RiArrowDropRightLine,
  RiArrowLeftRightFill,
  RiArrowDownSLine,
  RiAddFill,
  RiErrorWarningLine,
  RiAccountPinBoxFill,
  RiDeleteBinFill,
  RiCloseLine,
  RiCloseFill,
  RiCursorFill,
  RiNodeTree,
  RiSearchLine,
  RiContractRightLine,
  RiErrorWarningFill,
  RiInformation2Fill,
  RiCheckboxFill,
  RiUploadCloudFill,
  RiPlayFill,
  RiStopCircleFill,
  RiArrowLeftSLine,
  RiArrowRightSLine,
  RiSparklingFill,
  RiExternalLinkLine,
  RiCheckFill,
  RiCheckLine,
  RiArrowLeftLine,
  RiArrowRightLine,
  RiArrowDownLine,
  RiArrowUpLine,
  RiQuestionLine,
  RiInformationLine,
  RiAlertLine,
  RiSubtractFill
} from '@remixicon/react';

export const ICONS = {
  RiArrowUpSLine,
  RiThumbUpFill,
  RiThumbUpLine,
  RiThumbDownFill,
  RiThumbDownLine,
  RiLineChartLine,
  RiStickyNote2Fill,
  RiDeleteBinLine,
  RiDraggable,
  RiPuzzleFill,
  RiPriceTag3Fill,
  RiEdit2Fill,
  RiFileCopyFill,
  RiBookmarkLine,
  RiDeleteBin6Fill,
  RiMore2Line,
  RiCloseLargeLine,
  RiLayout3Line,
  RiTerminalBoxFill,
  RiTerminalWindowFill,
  RiCalculatorFill,
  RiCheckboxMultipleFill,
  RiHealthBookFill,
  RiSurveyFill,
  RiMessage3Fill,
  RiQuestionFill,
  RiAlertFill,
  RiArrowDropRightLine,
  RiArrowLeftRightFill,
  RiArrowDownSLine,
  RiAddFill,
  RiErrorWarningLine,
  RiAccountPinBoxFill,
  RiDeleteBinFill,
  RiCloseLine,
  RiCloseFill,
  RiCursorFill,
  RiNodeTree,
  RiSearchLine,
  RiContractRightLine,
  RiErrorWarningFill,
  RiInformation2Fill,
  RiCheckboxFill,
  RiUploadCloudFill,
  RiPlayFill,
  RiStopCircleFill,
  RiArrowLeftSLine,
  RiArrowRightSLine,
  RiSparklingFill,
  RiExternalLinkLine,
  RiCheckFill,
  RiCheckLine,
  RiArrowLeftLine,
  RiArrowRightLine,
  RiArrowDownLine,
  RiArrowUpLine,
  RiQuestionLine,
  RiInformationLine,
  RiAlertLine,
  RiSubtractFill
};

export enum IconSize {
  xs = 16,
  s = 20,
  m = 24,
  l = 28,
  xl = 32
}

export type IconType = keyof typeof ICONS;
