name: New version created

on:
  push:
    tags: ['*']

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{secrets.VERSION_BUMP_TOKEN}}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: yarn tailwind && yarn build

      - name: Setup .yarnrc.yml
        run: |
          yarn config set npmAlwaysAuth true
          yarn config set npmAuthToken $NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AWELL_EXTENSIONS_CI }}

      - name: Publish to NPM Registry
        run: |
          yarn npm publish
